#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/* automatically generated by rust-bindgen 0.59.1 */

extern "C" {
    pub fn precicec_createSolverInterface_withCommunicator(
        participantName: *const ::std::os::raw::c_char,
        configFileName: *const ::std::os::raw::c_char,
        solverProcessIndex: ::std::os::raw::c_int,
        solverProcessSize: ::std::os::raw::c_int,
        communicator: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn precicec_createSolverInterface(
        participantName: *const ::std::os::raw::c_char,
        configFileName: *const ::std::os::raw::c_char,
        solverProcessIndex: ::std::os::raw::c_int,
        solverProcessSize: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn precicec_initialize() -> f64;
}
extern "C" {
    pub fn precicec_initialize_data();
}
extern "C" {
    pub fn precicec_advance(computedTimestepLength: f64) -> f64;
}
extern "C" {
    pub fn precicec_finalize();
}
extern "C" {
    pub fn precicec_getDimensions() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_isCouplingOngoing() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_isReadDataAvailable() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_isWriteDataRequired(computedTimestepLength: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_isTimeWindowComplete() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_hasToEvaluateSurrogateModel() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_hasToEvaluateFineModel() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_isActionRequired(
        action: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_markActionFulfilled(action: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn precicec_hasMesh(meshName: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_getMeshID(meshName: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_setMeshVertex(
        meshID: ::std::os::raw::c_int,
        position: *const f64,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_getMeshVertexSize(meshID: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_setMeshVertices(
        meshID: ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
        positions: *const f64,
        ids: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn precicec_getMeshVertices(
        meshID: ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
        ids: *const ::std::os::raw::c_int,
        positions: *mut f64,
    );
}
extern "C" {
    pub fn precicec_getMeshVertexIDsFromPositions(
        meshID: ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
        positions: *const f64,
        ids: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn precicec_setMeshEdge(
        meshID: ::std::os::raw::c_int,
        firstVertexID: ::std::os::raw::c_int,
        secondVertexID: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_setMeshTriangle(
        meshID: ::std::os::raw::c_int,
        firstEdgeID: ::std::os::raw::c_int,
        secondEdgeID: ::std::os::raw::c_int,
        thirdEdgeID: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn precicec_setMeshTriangleWithEdges(
        meshID: ::std::os::raw::c_int,
        firstVertexID: ::std::os::raw::c_int,
        secondVertexID: ::std::os::raw::c_int,
        thirdVertexID: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn precicec_setMeshQuad(
        meshID: ::std::os::raw::c_int,
        firstEdgeID: ::std::os::raw::c_int,
        secondEdgeID: ::std::os::raw::c_int,
        thirdEdgeID: ::std::os::raw::c_int,
        fourthEdgeID: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn precicec_setMeshQuadWithEdges(
        meshID: ::std::os::raw::c_int,
        firstVertexID: ::std::os::raw::c_int,
        secondVertexID: ::std::os::raw::c_int,
        thirdVertexID: ::std::os::raw::c_int,
        fourthVertexID: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn precicec_hasData(
        dataName: *const ::std::os::raw::c_char,
        meshID: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_getDataID(
        dataName: *const ::std::os::raw::c_char,
        meshID: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn precicec_mapReadDataTo(toMeshID: ::std::os::raw::c_int);
}
extern "C" {
    pub fn precicec_mapWriteDataFrom(fromMeshID: ::std::os::raw::c_int);
}
extern "C" {
    pub fn precicec_writeBlockVectorData(
        dataID: ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
        valueIndices: *const ::std::os::raw::c_int,
        values: *const f64,
    );
}
extern "C" {
    pub fn precicec_writeVectorData(
        dataID: ::std::os::raw::c_int,
        valueIndex: ::std::os::raw::c_int,
        dataValue: *const f64,
    );
}
extern "C" {
    pub fn precicec_writeBlockScalarData(
        dataID: ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
        valueIndices: *const ::std::os::raw::c_int,
        values: *const f64,
    );
}
extern "C" {
    pub fn precicec_writeScalarData(
        dataID: ::std::os::raw::c_int,
        valueIndex: ::std::os::raw::c_int,
        dataValue: f64,
    );
}
extern "C" {
    pub fn precicec_readBlockVectorData(
        dataID: ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
        valueIndices: *const ::std::os::raw::c_int,
        values: *mut f64,
    );
}
extern "C" {
    pub fn precicec_readVectorData(
        dataID: ::std::os::raw::c_int,
        valueIndex: ::std::os::raw::c_int,
        dataValue: *mut f64,
    );
}
extern "C" {
    pub fn precicec_readBlockScalarData(
        dataID: ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
        valueIndices: *const ::std::os::raw::c_int,
        values: *mut f64,
    );
}
extern "C" {
    pub fn precicec_readScalarData(
        dataID: ::std::os::raw::c_int,
        valueIndex: ::std::os::raw::c_int,
        dataValue: *mut f64,
    );
}
extern "C" {
    pub fn precicec_getVersionInformation() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn precicec_actionWriteInitialData() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn precicec_actionWriteIterationCheckpoint() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn precicec_actionReadIterationCheckpoint() -> *const ::std::os::raw::c_char;
}